name: Build AlefTaya IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ldid (For TrollStore Entitlements)
        run: brew install ldid

      - name: Build Xcode Project
        run: |
          mkdir -p build
          xcodebuild -project GoogleFrontProxy.xcodeproj \
            -scheme GoogleFrontProxy \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            IPHONEOS_DEPLOYMENT_TARGET=15.0

      - name: Inject Entitlements & Create IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/GoogleFrontProxy.app Payload/
          
          # ۱. دادن اجازه اجرای مستقیم به فایل راست
          chmod +x Payload/GoogleFrontProxy.app/MasterHttpRelay-iOS
          
          # ۲. پیدا کردن مسیر دقیق فایل تنظیمات به صورت خودکار
          ENT_PATH=$(find . -name "Entitlements.plist" | head -n 1)
          echo "Found Entitlements at: $ENT_PATH"
          
          # ۳. تزریق تنظیمات با آدرس دقیق به اپلیکیشن
          ldid -S"$ENT_PATH" Payload/GoogleFrontProxy.app/GoogleFrontProxy
          
          zip -r aleftaya_proxy.ipa Payload
          
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: aleftaya-proxy-ios
          path: aleftaya_proxy.ipa
